version: '2.3'

services:
  terracotta-bank:
    image: terracotta-bank:0.0.1-SNAPSHOT
    ports:
      - "8080:80"

  selenium_grid:
    image: dosel/zalenium
    entrypoint: ${SELENIUM_GRID_ENTRYPOINT:-/bin/true}
    ports:
      - "4444:4444"
    command:
      - start
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true

  selenium_grid_dependency:
    image: elgalu/selenium:3.11.0-p5

  owasp-zap:
    image: owasp/zap2docker-stable:latest
    ports:
      - "8090:8090"
    command:
      zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true
